### ISSUE TITLE
Null pointer in dispatchQueueBatch v2.1.1

### ISSUE THREAD

**Issue by sanimalp** [graphql-java/java-dataloader#80]
https://github.com/graphql-java/java-dataloader/blob/19234f106f464d3a54f647f3a0ef4f783a1a56dd/src/main/java/org/dataloader/DataLoaderHelper.java#L200

We have gotten a couple exceptions running in production around the above line of code. The trace is: 

```
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at org.dataloader.DataLoaderHelper.lambda$dispatchQueueBatch$2(DataLoaderHelper.java:200)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException: null
```

We are going to take a look at this on priority at some point coming up here, but wanted to drop it here in case the solution is obvious in some way. Any insight is certainly welcome as well.

**Comment by bbakerman** [comment]
any news?  closing for now
